#!/bin/bash
# Download Latest WP Core, create a wp-config.php file, create a database,
# and initailize a new user for the WordPress install
#
# This script assumes that you already have WP-CLI installed
#
# Execute this script inside the directory you want a WordPress install in
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [[ -z "$1" ]]
  then
    echo -e "${RED}Usage${NC}: Please supply the local SITE URL in the first parameter"
    exit 1
fi

if [[ -z "$2" ]]
  then
    echo -e "${RED}Usage${NC}: Please supply the SITE TITLE in the second parameter"
    exit 1
fi

if [[ -z "$3" ]]
  then
    echo -e "${RED}Usage${NC}: Please supply the USERNAME in the third parameter"
    exit 1
fi

if [[ -z "$4" ]]
  then
    echo -e "${RED}Usage${NC}: Please supply the ADMIN EMAIL in the forth parameter"
    exit 1
fi

 # download WordPress
wp core download

# Prompt user on wp-config.php settings
wp config create --prompt

# Create database
wp db create

# Init WP Core
wp core install --url=https://$1/ --title=$2 --admin_user=$3 --admin_password=Password1 --admin_email=$4

# Get rid of default themes
wp theme delete twentyseventeen twentysixteen twentyfifteen

# Get rid of default plugins
wp plugin delete akismet hello
echo -e "\nUpdating Apache ${RED}httpd-vhosts${NC} and ${RED}/etc/hosts${NC} file with the URL and PATH you specified"

echo -e "\n${RED}URL:${NC} https://$1/"
echo -e "${RED}PATH:${NC} `pwd`"
echo "<VirtualHost *:443>
    SSLEngine On
    SSLCertificateFile /Users/sumnererhard/ssl/server.crt
    SSLCertificateKeyFile /Users/sumnererhard/ssl/server.key

    ServerAdmin localhost
    DocumentRoot "\"`pwd`\""
    ServerName "\"$1"\"
    ErrorLog "\"/Applications/MAMP/logs/$2-error_log"\"
</VirtualHost>" >> /Applications/MAMP/conf/apache/extra/httpd-vhosts.conf
echo -e "\n${GREEN}Complete${NC} httpd-vhosts.conf file updated"

echo -e "\nPlease enter your password in order to update your /etc/hosts file"
echo "127.0.0.1   $1" | sudo tee -a /etc/hosts >> /dev/null
echo -e "\n${GREEN}Complete${NC}: /etc/host file updated"

echo -e "\n${GREEN}Install Complete${NC}"
echo -e "\n${RED}USERNAME:${NC} $3"
echo -e "\n${RED}PASS:${NC} Password1"

echo -e "\nManaully restart MAMP"
