#!/bin/bash
# Download Latest WP Core, create a wp-config.php file, create a database,
# and initailize a new user for the WordPress install
#
# This script assumes that you already have WP-CLI installed
#
# Execute this script inside the directory you want a WordPress install in

USAGE() {
    echo -e "Usage: ${GREEN}$PROGRAM www.mysite.com mysite JohnDoe jd@fakeemail.com${NC}"
    echo -e "Parameter 1: Please supply the local ${GREEN}SITE URL${NC}"
    echo -e "Parameter 2: Please supply the local ${GREEN}SITE TITLE${NC}"
    echo -e "Parameter 3: Please supply the local ${GREEN}USERNAME${NC}"
    echo -e "Parameter 4: Please supply the local ${GREEN}ADMIN EMAIL${NC}"
    echo "If you have not already, install the WP-CLI command line tool."
    echo "Then execute this script inside the directory you want WordPress installed in."
    exit 1
}

# Emit a message to stderr and exit.
die() {
    echo "$@" >&2
    exit 1
}

declare -r RED='\033[0;31m'
declare -r GREEN='\033[0;32m'
declare -r NC='\033[0m' # No Color
declare -r PROGRAM=${0##*/} #basename of program

if [[ $# -ne 4 ]]; then
    USAGE
fi

declare -r _site_url=$1
declare -r _site_title=$2
declare -r _username=$3
declare -r _admin_email=$4

echo -e "site url   : $_site_url"
echo -e "site title : $_site_title"
echo -e "username   : $_username"
echo -e "email      : $_admin_email"

die 'end of current completion'

 # download WordPress
wp core download

# Prompt user on wp-config.php settings
wp config create --prompt

# Create database
wp db create

# Init WP Core
wp core install --url=https://$_site_url/ --title=$_site_title --admin_user=$_username --admin_password=Password1 --admin_email=$_admin_email

# Get rid of default themes
wp theme delete twentyseventeen twentysixteen twentyfifteen

# Get rid of default plugins
wp plugin delete akismet hello
echo -e "\nUpdating Apache ${RED}httpd-vhosts${NC} and ${RED}/etc/hosts${NC} file with the URL and PATH you specified"

echo -e "\n${RED}URL:${NC} https://$_site_url/"
echo -e "${RED}PATH:${NC} `pwd`"

# Change the location of the SSL certificate to the path on your system
echo "<VirtualHost *:443>
    SSLEngine On
    SSLCertificateFile /Users/sumnererhard/ssl/server.crt
    SSLCertificateKeyFile /Users/sumnererhard/ssl/server.key

    ServerAdmin localhost
    DocumentRoot "\"`pwd`\""
    ServerName "\"$_site_url"\"
    ErrorLog "\"/Applications/MAMP/logs/$_site_title-error_log"\"
</VirtualHost>" >> /Applications/MAMP/conf/apache/extra/httpd-vhosts.conf
echo -e "\n${GREEN}Complete${NC} httpd-vhosts.conf file updated"

echo -e "\nPlease enter your password in order to update your /etc/hosts file"
echo "127.0.0.1   $_site_url" | sudo tee -a /etc/hosts >> /dev/null
echo -e "\n${GREEN}Complete${NC}: /etc/host file updated"

echo -e "\n${GREEN}Install Complete${NC}"
echo -e "\n${RED}USERNAME:${NC} $_username"
echo -e "\n${RED}PASS:${NC} Password1"

echo -e "\nManaully restart MAMP"
